/* 
 * File:   MCAL_Interrupt_Gen_CFG.h
 * Author: Eng.Yassmin
 *
 * Created on November 1, 2024, 1:18 PM
 */

#ifndef MCAL_INTERRUPT_GEN_CFG_H
#define	MCAL_INTERRUPT_GEN_CFG_H
/* Includes Section */
#define INTERRUPT_FEATURE_ENABLE    1
/* Macro Declaration Section */
//#define INTERRUPT_PRIO_LEVEL_ENABLE                   INTERRUPT_FEATURE_ENABLE 
#define INTERRUPT_EXTERNAL_FEATURE_INTx_ENABLE        INTERRUPT_FEATURE_ENABLE 
#define INTERRUPT_EXTERNAL_FEATURE_OnChange_ENABLE    INTERRUPT_FEATURE_ENABLE 
#define ADC_INTERRUPT_FEATURE_ENABLE                  INTERRUPT_FEATURE_ENABLE
#define TIMER0_INTERRUPT_FEATURE_ENABLE               INTERRUPT_FEATURE_ENABLE
#define TIMER1_INTERRUPT_FEATURE_ENABLE               INTERRUPT_FEATURE_ENABLE
#define TIMER2_INTERRUPT_FEATURE_ENABLE               INTERRUPT_FEATURE_ENABLE
#define TIMER3_INTERRUPT_FEATURE_ENABLE               INTERRUPT_FEATURE_ENABLE
#define CCP1_INTERRUPT_FEATURE_ENABLE                 INTERRUPT_FEATURE_ENABLE
#define CCP2_INTERRUPT_FEATURE_ENABLE                 INTERRUPT_FEATURE_ENABLE
#define USART_TX_INTERRUPT_FEATURE_ENABLE             INTERRUPT_FEATURE_ENABLE
#define USART_RX_INTERRUPT_FEATURE_ENABLE             INTERRUPT_FEATURE_ENABLE
//#define I2C_INTERRUPT_FEATURE_ENABLE                  INTERRUPT_FEATURE_ENABLE
/* Macro Function Declaration Section */

/* Data Type Section */

/* Function Declaration Section */


#endif	/* MCAL_INTERRUPT_GEN_CFG_H */

